import { WingetPackage } from './types'

export const mockPackages: WingetPackage[] = [
  {
    id: 'Microsoft.VisualStudioCode',
    name: 'Visual Studio Code',
    publisher: 'Microsoft',
    version: '1.85.0',
    description: 'Code editing. Redefined. Free. Built on open source. Runs everywhere.',
    homepage: 'https://code.visualstudio.com',
    license: 'MIT',
    tags: ['editor', 'ide', 'development', 'programming'],
    installCommand: 'winget install --id Microsoft.VisualStudioCode',
    category: 'Development'
  },
  {
    id: 'Git.Git',
    name: 'Git',
    publisher: 'Git',
    version: '2.43.0',
    description: 'Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.',
    homepage: 'https://git-scm.com',
    license: 'GPL-2.0',
    tags: ['vcs', 'version-control', 'development'],
    installCommand: 'winget install --id Git.Git',
    category: 'Development'
  },
  {
    id: 'Google.Chrome',
    name: 'Google Chrome',
    publisher: 'Google',
    version: '120.0.6099.130',
    description: 'A fast, secure, and free web browser built for the modern web.',
    homepage: 'https://www.google.com/chrome/',
    license: 'Proprietary',
    tags: ['browser', 'web', 'google'],
    installCommand: 'winget install --id Google.Chrome',
    category: 'Web Browsers'
  },
  {
    id: 'Mozilla.Firefox',
    name: 'Mozilla Firefox',
    publisher: 'Mozilla',
    version: '121.0',
    description: 'Free and open-source web browser developed by the Mozilla Foundation.',
    homepage: 'https://www.mozilla.org/firefox/',
    license: 'MPL-2.0',
    tags: ['browser', 'web', 'mozilla', 'open-source'],
    installCommand: 'winget install --id Mozilla.Firefox',
    category: 'Web Browsers'
  },
  {
    id: 'Python.Python.3.12',
    name: 'Python 3.12',
    publisher: 'Python Software Foundation',
    version: '3.12.1',
    description: 'Python is a programming language that lets you work quickly and integrate systems more effectively.',
    homepage: 'https://www.python.org',
    license: 'PSF',
    tags: ['python', 'programming', 'development', 'language'],
    installCommand: 'winget install --id Python.Python.3.12',
    category: 'Development'
  },
  {
    id: 'OpenJS.NodeJS',
    name: 'Node.js',
    publisher: 'OpenJS Foundation',
    version: '20.10.0',
    description: 'Node.js is a JavaScript runtime built on Chrome\'s V8 JavaScript engine.',
    homepage: 'https://nodejs.org',
    license: 'MIT',
    tags: ['nodejs', 'javascript', 'runtime', 'development'],
    installCommand: 'winget install --id OpenJS.NodeJS',
    category: 'Development'
  },
  {
    id: 'Docker.DockerDesktop',
    name: 'Docker Desktop',
    publisher: 'Docker Inc.',
    version: '4.26.1',
    description: 'Docker Desktop is an easy-to-install application for your Mac, Linux, or Windows environment that enables you to build and share containerized applications.',
    homepage: 'https://www.docker.com/products/docker-desktop',
    license: 'Proprietary',
    tags: ['docker', 'container', 'virtualization', 'development'],
    installCommand: 'winget install --id Docker.DockerDesktop',
    category: 'Development'
  },
  {
    id: 'Microsoft.PowerShell',
    name: 'PowerShell',
    publisher: 'Microsoft',
    version: '7.4.1',
    description: 'PowerShell is a cross-platform task automation solution made up of a command-line shell, a scripting language, and a configuration management framework.',
    homepage: 'https://github.com/PowerShell/PowerShell',
    license: 'MIT',
    tags: ['powershell', 'shell', 'scripting', 'automation'],
    installCommand: 'winget install --id Microsoft.PowerShell',
    category: 'Tools'
  },
  {
    id: 'Notepad++.Notepad++',
    name: 'Notepad++',
    publisher: 'Notepad++',
    version: '8.6.1',
    description: 'Notepad++ is a free source code editor and Notepad replacement that supports several languages.',
    homepage: 'https://notepad-plus-plus.org',
    license: 'GPL-3.0',
    tags: ['editor', 'text', 'development', 'open-source'],
    installCommand: 'winget install --id Notepad++.Notepad++',
    category: 'Development'
  },
  {
    id: 'VideoLAN.VLC',
    name: 'VLC Media Player',
    publisher: 'VideoLAN',
    version: '3.0.20',
    description: 'VLC is a free and open source cross-platform multimedia player and framework.',
    homepage: 'https://www.videolan.org/vlc/',
    license: 'GPL-2.0',
    tags: ['media', 'player', 'video', 'audio', 'open-source'],
    installCommand: 'winget install --id VideoLAN.VLC',
    category: 'Media'
  },
  {
    id: '7zip.7zip',
    name: '7-Zip',
    publisher: '7-Zip',
    version: '23.01',
    description: '7-Zip is a file archiver with a high compression ratio.',
    homepage: 'https://www.7-zip.org',
    license: 'LGPL-2.1',
    tags: ['compression', 'archiver', 'utility', 'open-source'],
    installCommand: 'winget install --id 7zip.7zip',
    category: 'Utilities'
  },
  {
    id: 'Microsoft.WindowsTerminal',
    name: 'Windows Terminal',
    publisher: 'Microsoft',
    version: '1.19.10302.0',
    description: 'The new Windows Terminal and the original Windows console host, all in the same place.',
    homepage: 'https://github.com/microsoft/terminal',
    license: 'MIT',
    tags: ['terminal', 'console', 'shell', 'command-line'],
    installCommand: 'winget install --id Microsoft.WindowsTerminal',
    category: 'Tools'
  },
  {
    id: 'GitHub.GitHubDesktop',
    name: 'GitHub Desktop',
    publisher: 'GitHub',
    version: '3.3.7',
    description: 'Simple collaboration from your desktop.',
    homepage: 'https://desktop.github.com',
    license: 'MIT',
    tags: ['git', 'github', 'vcs', 'development'],
    installCommand: 'winget install --id GitHub.GitHubDesktop',
    category: 'Development'
  },
  {
    id: 'JetBrains.IntelliJIDEA.Community',
    name: 'IntelliJ IDEA Community Edition',
    publisher: 'JetBrains',
    version: '2023.3.2',
    description: 'Capable and Ergonomic Java IDE for Enterprise, Web and Mobile Development.',
    homepage: 'https://www.jetbrains.com/idea/',
    license: 'Apache-2.0',
    tags: ['ide', 'java', 'development', 'jetbrains'],
    installCommand: 'winget install --id JetBrains.IntelliJIDEA.Community',
    category: 'Development'
  },
  {
    id: 'Discord.Discord',
    name: 'Discord',
    publisher: 'Discord Inc.',
    version: '1.0.9024',
    description: 'All-in-one voice and text chat for gamers that\'s free, secure, and works on both your desktop and phone.',
    homepage: 'https://discord.com',
    license: 'Proprietary',
    tags: ['chat', 'voice', 'gaming', 'communication'],
    installCommand: 'winget install --id Discord.Discord',
    category: 'Communication'
  },
  {
    id: 'Spotify.Spotify',
    name: 'Spotify',
    publisher: 'Spotify AB',
    version: '1.2.29.964',
    description: 'Digital music service that gives you access to millions of songs.',
    homepage: 'https://www.spotify.com',
    license: 'Proprietary',
    tags: ['music', 'streaming', 'audio', 'media'],
    installCommand: 'winget install --id Spotify.Spotify',
    category: 'Media'
  },
  {
    id: 'Microsoft.Teams',
    name: 'Microsoft Teams',
    publisher: 'Microsoft',
    version: '23326.406.2374.4397',
    description: 'Meet, chat, call, and collaborate in just one place.',
    homepage: 'https://www.microsoft.com/microsoft-teams',
    license: 'Proprietary',
    tags: ['chat', 'collaboration', 'communication', 'video'],
    installCommand: 'winget install --id Microsoft.Teams',
    category: 'Communication'
  },
  {
    id: 'Postman.Postman',
    name: 'Postman',
    publisher: 'Postman',
    version: '10.20.3',
    description: 'Postman is an API platform for building and using APIs.',
    homepage: 'https://www.postman.com',
    license: 'Proprietary',
    tags: ['api', 'development', 'testing', 'http'],
    installCommand: 'winget install --id Postman.Postman',
    category: 'Development'
  },
  {
    id: 'SlackTechnologies.Slack',
    name: 'Slack',
    publisher: 'Slack Technologies',
    version: '4.35.131',
    description: 'Slack is a new way to communicate with your team. It\'s faster, better organized, and more secure than email.',
    homepage: 'https://slack.com',
    license: 'Proprietary',
    tags: ['chat', 'collaboration', 'communication', 'team'],
    installCommand: 'winget install --id SlackTechnologies.Slack',
    category: 'Communication'
  },
  {
    id: 'Zoom.Zoom',
    name: 'Zoom',
    publisher: 'Zoom Video Communications',
    version: '5.16.10',
    description: 'Video conferencing, web conferencing, webinars, screen sharing.',
    homepage: 'https://zoom.us',
    license: 'Proprietary',
    tags: ['video', 'conference', 'meeting', 'communication'],
    installCommand: 'winget install --id Zoom.Zoom',
    category: 'Communication'
  },
  {
    id: 'Valve.Steam',
    name: 'Steam',
    publisher: 'Valve',
    version: '2.10.91.91',
    description: 'The ultimate entertainment platform.',
    homepage: 'https://store.steampowered.com',
    license: 'Proprietary',
    tags: ['gaming', 'games', 'platform', 'store'],
    installCommand: 'winget install --id Valve.Steam',
    category: 'Gaming'
  },
  {
    id: 'Oracle.VirtualBox',
    name: 'Oracle VM VirtualBox',
    publisher: 'Oracle',
    version: '7.0.12',
    description: 'VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use.',
    homepage: 'https://www.virtualbox.org',
    license: 'GPL-2.0',
    tags: ['virtualization', 'vm', 'virtual-machine', 'development'],
    installCommand: 'winget install --id Oracle.VirtualBox',
    category: 'Utilities'
  },
  {
    id: 'WinSCP.WinSCP',
    name: 'WinSCP',
    publisher: 'WinSCP',
    version: '6.2.1',
    description: 'WinSCP is a popular free SFTP and FTP client for Windows, a powerful file manager that will improve your productivity.',
    homepage: 'https://winscp.net',
    license: 'GPL-3.0',
    tags: ['ftp', 'sftp', 'file-transfer', 'ssh'],
    installCommand: 'winget install --id WinSCP.WinSCP',
    category: 'Utilities'
  },
  {
    id: 'Brave.Brave',
    name: 'Brave Browser',
    publisher: 'Brave Software',
    version: '1.61.109',
    description: 'The Brave browser is a fast, private and secure web browser for PC, Mac and mobile.',
    homepage: 'https://brave.com',
    license: 'MPL-2.0',
    tags: ['browser', 'web', 'privacy', 'open-source'],
    installCommand: 'winget install --id Brave.Brave',
    category: 'Web Browsers'
  },
  {
    id: 'Adobe.Acrobat.Reader.64-bit',
    name: 'Adobe Acrobat Reader DC',
    publisher: 'Adobe',
    version: '23.008.20470',
    description: 'The free global standard for reliably viewing, printing, and commenting on PDF documents.',
    homepage: 'https://get.adobe.com/reader/',
    license: 'Proprietary',
    tags: ['pdf', 'reader', 'document', 'viewer'],
    installCommand: 'winget install --id Adobe.Acrobat.Reader.64-bit',
    category: 'Utilities'
  },
  {
    id: 'OBSProject.OBSStudio',
    name: 'OBS Studio',
    publisher: 'OBS Project',
    version: '30.0.2',
    description: 'Free and open source software for video recording and live streaming.',
    homepage: 'https://obsproject.com',
    license: 'GPL-2.0',
    tags: ['streaming', 'recording', 'video', 'broadcast', 'open-source'],
    installCommand: 'winget install --id OBSProject.OBSStudio',
    category: 'Media'
  },
  {
    id: 'Microsoft.DotNet.SDK.8',
    name: '.NET SDK 8',
    publisher: 'Microsoft',
    version: '8.0.101',
    description: '.NET is a free, cross-platform, open source developer platform for building many different types of applications.',
    homepage: 'https://dotnet.microsoft.com',
    license: 'MIT',
    tags: ['dotnet', 'sdk', 'development', 'framework'],
    installCommand: 'winget install --id Microsoft.DotNet.SDK.8',
    category: 'Development'
  },
  {
    id: 'Figma.Figma',
    name: 'Figma',
    publisher: 'Figma',
    version: '116.16.4',
    description: 'The collaborative interface design tool.',
    homepage: 'https://www.figma.com',
    license: 'Proprietary',
    tags: ['design', 'ui', 'ux', 'prototyping'],
    installCommand: 'winget install --id Figma.Figma',
    category: 'Design'
  },
  {
    id: 'Audacity.Audacity',
    name: 'Audacity',
    publisher: 'Audacity Team',
    version: '3.4.2',
    description: 'Free, open source, cross-platform audio software for multi-track recording and editing.',
    homepage: 'https://www.audacityteam.org',
    license: 'GPL-2.0',
    tags: ['audio', 'editor', 'recording', 'music', 'open-source'],
    installCommand: 'winget install --id Audacity.Audacity',
    category: 'Media'
  },
  {
    id: 'Notion.Notion',
    name: 'Notion',
    publisher: 'Notion Labs',
    version: '2.2.3',
    description: 'All-in-one workspace for your notes, tasks, wikis, and databases.',
    homepage: 'https://www.notion.so',
    license: 'Proprietary',
    tags: ['notes', 'productivity', 'collaboration', 'workspace'],
    installCommand: 'winget install --id Notion.Notion',
    category: 'Productivity'
  },
  {
    id: 'Bitwarden.Bitwarden',
    name: 'Bitwarden',
    publisher: 'Bitwarden',
    version: '2023.12.0',
    description: 'A secure and free password manager for all of your devices.',
    homepage: 'https://bitwarden.com',
    license: 'GPL-3.0',
    tags: ['password', 'security', 'encryption', 'open-source'],
    installCommand: 'winget install --id Bitwarden.Bitwarden',
    category: 'Security'
  }
]
